apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}-{{ .Values.env }}
  namespace: {{ .Values.service.namespace }}
  labels:
    app: {{ .Values.app }}-{{ .Values.env }}
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    name: {{ .Values.app }}-{{ .Values.env }}
  selector:
    app: {{ .Values.app }}-{{ .Values.env }}
