apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springbootsample-{{ .Values.env }}
spec:
  destination:
    namespace: {{ .Values.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.project }}
  source:
    path: {{ .Values.spec.source.path }}
    repoURL: {{ .Values.spec.source.repo }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - values-dev.yaml
        - values.yaml
  syncPolicy: {}
