env: dev
build: dev

service:
  namespace: dev

resources:
  limits:
    memory: 1000Mi
    cpu: 1.2
  requests:
    cpu: 1
    memory: 800Mi
hpa:
  replicas:
    min: 2
    max: 20
  metrics:
    memory: 60
    cpu: 60
