env: dev
build: dev

service:
  namespace: dev

resources:
  limits:
    memory: 100Mi
    cpu: 1
  requests:
    cpu: 1
    memory: 100Mi
hpa:
  replicas:
    min: 1
    max: 5
  metrics:
    memory: 60
    cpu: 60
