env: dev
build: dev

service:
  namespace: dev

resources:
  limits:
    memory: 200Mi
    cpu: 200m
  requests:
    cpu: 200m
    memory: 200Mi
hpa:
  replicas:
    min: 1
    max: 5
  metrics:
    memory: 60
    cpu: 60
