apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::872802577141:role/dev20200721025447156700000007
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
